# Generated by Django 4.2.1 on 2023-09-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_setting_contact_alter_setting_smtpemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='contact',
            field=models.TextField(blank=True),
        ),
    ]
